CREATE TABLE USERS(
	UID VARCHAR(20) NOT NULL, 
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	PRIMARY KEY (UID)
)

create table ARTICLES (
	ID int not null,
	OWNER VARCHAR(20) not null,
	WRITER VARCHAR(20) not null,
	SUBJECT VARCHAR(300) not null,
	CONTENT CLOB,
	CREATE_DATE DATE,
	UPDATE_DATE DATE,
	PRIMARY KEY(ID),
	FOREIGN KEY (OWNER) REFERENCES USERS(UID),
	FOREIGN KEY (WRITER) REFERENCES USERS(UID)
)
