CREATE TABLE USERS(
	UID VARCHAR(20) NOT NULL, 
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	PRIMARY KEY (UID)
)

create table CATEGORIES (
	ID int not null,
	OWNER VARCHAR(20) not null,
	title VARCHAR(100) not null,
	PARENT int,
	LEAF boolean,
	PRIMARY KEY(ID),
	FOREIGN KEY (OWNER) REFERENCES USERS(UID)
)

CREATE SEQUENCE CATEGORY_SEQ AS INT 
	START WITH 1 
	INCREMENT BY 1
	MAXVALUE 2147483647


create table ARTICLES (
	ID int not null,
	OWNER VARCHAR(20) not null,
	WRITER VARCHAR(20) not null,
	SUBJECT VARCHAR(300) not null,
	CONTENT CLOB,
	CATEGORY int not null,
	CREATE_DATE DATE,
	UPDATE_DATE DATE,
	PRIMARY KEY(ID),
	FOREIGN KEY (OWNER) REFERENCES USERS(UID),
	FOREIGN KEY (WRITER) REFERENCES USERS(UID)
)

CREATE SEQUENCE ARTICLE_SEQ AS INT 
	START WITH 1 
	INCREMENT BY 1
	MAXVALUE 2147483647
